version: 1.0.{build}
configuration: Release
image: Visual Studio 2015
environment:
  nodejs_version: "7.7.3"
install:
- ps: Install-Product node $env:nodejs_version
- node -v
- npm install -g cmake-js
- npm install -g typescript
- npm install
- set PATH=C:\Users\appveyor\AppData\Roaming\npm;%PATH%
- tsc
build_script:
- cmd: node build
artifacts:
- path: gameplay*.zip
  name: gameplay.zip
deploy:
- provider: GitHub
  tag: '%APPVEYOR_REPO_TAG_NAME%'
  auth_token:
    secure: TcTgvgqFgep3CawLJfghwhG4VwcZm6+c4GwCdLXg4zUFktqUEWQXkn4QQUG3WOxY
  artifact: gameplay.zip
  draft: true
  on:
    APPVEYOR_REPO_TAG: true